module.exports = {
  brew: [
    // http://conqueringthecommandline.com/book/ack_ag
    'ack',
    'ag',
    'adns',
    // https://github.com/wting/autojump
    'autojump',
    // alternative to `cat`: https://github.com/sharkdp/bat
    'bat',
    'brew-cask-completion',
    // Install GNU core utilities (those that come with macOS are outdated)
    // Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
    'coreutils',
    'cowsay',
    'docker-completion',
    'docker-compose-completion  libunistring',
    'dos2unix',
    // Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
    'findutils',
    'fontconfig',
    'freetype',
    'fortune',
    'fzf',
    'readline', // ensure gawk gets good readline
    'gawk',
    'gdbm',
    'gettext',
    // http://www.lcdf.org/gifsicle/ (because I'm a gif junky)
    'gifsicle',
    'git',
    'git-credential-manager',
    'gmp',
    'gnupg',
    'gnutls',
    // Install GNU `sed`, overwriting the built-in `sed`
    // so we can do "sed -i 's/foo/bar/' file" instead of "sed -i '' 's/foo/bar/' file"
    'gnu-sed --with-default-names',
    // upgrade grep so we can get things like inverted match (-v)
    'grep --with-default-names',
    // better, more recent grep
    'homebrew/dupes/grep',
    // https://github.com/jkbrzt/httpie
    'httpie',
    'icu4c',
    // jq is a sort of JSON grep
    'jq',
    'lazygit',
    'libassuan',
    'libevent',
    'libffi',
    'libgcrypt',
    'libgpg-error',
    'libidn2',
    'libksba',
    'libpng',
    'libtasn1',
    'libusb',
    'libyaml',
    // Mac App Store CLI: https://github.com/mas-cli/mas
    'mas',
    'maven',
    'maven-completion',
    // Install some other useful utilities like `sponge`
    'moreutils',
    'mpfr',
    'ncurses',
    'nettle',
    'nmap',
    'node',
    'npth',
    'nvm',
    'oniguruma',
    // 'openconnect',
    'openjdk',
    'openssl@1.1',
    'p11-kit',
    'pcre',
    'pcre2',
    'pinentry',
    'python',
    'python@3.8',
    'readline',
    'reattach-to-user-namespace',
    // better/more recent version of screen
    'ruby',
    'sqlite',
    'stoken',
    'homebrew/dupes/screen',
    'telnet',
    'the_silver_searcher',
    'tmux',
    'todo-txt',
    'tree',
    'ttyrec',
    'unbound',
    // better, more recent vim
    'vim --with-client-server --with-override-system-vi',
    'watch',
    'watchman',
    // Install wget with IRI support
    'wget --enable-iri',
    'xz',
    'yarn',
    'yarn-completion',
    'zsh',
    'zsh-autosuggestions',
    'zsh-completions',
    'zsh-git-prompt',
    'zsh-history-substring-search',
    'zsh-lovers',
    'zsh-navigation-tools',
    'zsh-syntax-highlighting',
  ],
  cask: [
    '1password',
    'acorn',
    'aerial',
    'adoptopenjdk8',
    'alfred',
    'caffeine',
    'dash',
    'diffmerge',
    'disk-inventory-x',
    'docker', // docker for mac
    'dropbox',
    // 'evernote',
    'firefox',
    'flux',
    'font-awesome-terminal-fonts',
    'font-fontawesome',
    'font-hack',
    'font-hack-nerd-font',
    'font-inconsolata-dz-for-powerline',
    'font-inconsolata-for-powerline',
    'font-inconsolata-g-for-powerline',
    'font-meslo-for-powerline',
    'font-meslo-lg',
    'font-meslo-nerd-font',
    'font-meslo-nerd-font-mono',
    'font-powerline-symbols',
    'font-roboto-mono',
    'font-roboto-mono-for-powerline',
    'font-source-code-pro',
    'font-source-code-pro-for-powerline',
    'font-sourcecodepro-nerd-font',
    'font-sourcecodepro-nerd-font-mono',
    'free-ruler',
    'fujitsu-scansnap-manager',
    'google-chrome',
    'gpg-suite',
    'handbrake',
    'haptickey',
    //'ireadfast',
    'intellij-idea',
    'iterm2',
    'java',
    'little-snitch',
    'macbreakz',
    'macpass',
    'micro-snitch',
    'microsoft-edge',
    'microsoft-office',
    'microsoft-teams',
    'omnifocus',
    'omnigraffle',
    'omnioutliner',
    'omniplan',
    'plex-media-player',
    'pock',
    'send-to-kindle',
    'shiftit',
    'signal',
    //'macvim',
    //'sizeup',
    //'sketchup',
    'skype',
    'slack',
    'sonos',
    'spamsieve',
    'sublime-text',
    'synology-chat',
    'synology-drive',
    'telegram',
    'the-unarchiver',
    'tor-browser',
    //'transmission',
    'visual-studio-code',
    //'vlc',
    'xquartz'
  ],
  gem: [
  ],
  npm: [
    'antic',
    //'buzzphrase',
    'eslint',
    //'instant-markdown-d',
    // 'generator-dockerize',
    // 'gulp',
    'npm-check-updates',
    //'prettyjson',
    //'trash',
    //'vtop'
    // ,'yo'
  ],
  mas: [
    //com.apple.dt.Xcode (10.2.1)
    '497799835',
    //com.if.Amphetamine (4.1.6)
    //'937984704',
    //net.shinyfrog.bear (1.6.15)
    //'1091189122',
    //com.monosnap.monosnap (3.5.8)
    //'540348655',
    //com.app77.pwsafemac (4.17)
    //'520993579',
  ],
};
